### PR TITLE
Combine `LAsort` w/ `daligner` jobs

### PR DESCRIPTION
**Pull request by pb-cdunn**
Combine `LAsort` w/ `daligner` jobs

This should reduce some network copying and might balance the jobs
better too.

Also, a nice functional test.

This works for me, both locally and in SGE. It definitely copies less data. I have not tested runtime impact, but it will affect NFS users more than us (on lustre).

### CODE REVIEW

**Comment by pb-jchin** [comment]
IIRC, "mv" is used when there is L3 merging. I need to check it out.

**Comment by pb-cdunn** [comment]
Ok. This should have no impact on 'mv'. Removed that TODO.

**Comment by pb-jchin** [comment]
for reference, the "mv" line is generate by https://github.com/PacificBiosciences/DALIGNER/blob/master/HPCdaligner.c line 501

**Comment by pb-cdunn** [comment]
This is solid code, and the functional test has 100% line-coverage. I'll merge this soon if there is no objection. Only FALCON-integrate releases (aka tags) need rigorous testing. We can always undo.

**Pull request merged**
