### PR TITLE
Fix #118

### LINKED ISSUE #118: bug in fc_ovlp_filter.py
See "BUGGY" at [this line](../blob/master/test/test_ovlp_filter.py#L16) of `filter_stage1()`. (Can't grep for "BUG" b/c "DEBUG" is everywhere.) I don't think `None` should appear there. Fix that, and add more (hopefully small) functional tests.

Impact: Tiny. This only fails to filter the first read, I think. Not sure though. I don't have time to look into it today.

### PR DESCRIPTION
**Pull request by pb-cdunn**
This will fix #118.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Jason, Do the bug-fixes look correct? I think they impact only very rare cases, but they break my tests.

**Comment by pb-jchin** [comment]
@pb-cdunn I am in a conference, it is a little dangerous to go code like this in a multitasking mode.  Once I have time for 100% focusing on the code. I will let you know.

**Comment by pb-cdunn** [comment]
Understood. I will wait.

**Comment by pb-jchin** [comment]
The changes look good. Thanks.

**Pull request merged**
