### PR TITLE
Added support for SLURM job scheduler

### PR DESCRIPTION
**Pull request by rlleras**
Already tested on HPC running SLURM. Note that each FALCON job will generate a separate log file, future update will optimize HPC log outputs to only be 1 file.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
@rlleras, You are not based on the latest code. I have rebased this for you (PacificBiosciences#107), but would you then be willing to switch to our new *master* branch?

**Comment by rlleras** [comment]
Yes absolutely that's fine.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Jun 24, 2015 at 8:15 AM -0700, "Christopher Dunn" <notifications@github.com<mailto:notifications@github.com>> wrote:


@rlleras<https://github.com/rlleras>, You are not based on the latest code. I have rebased this for you (PacificBiosciences#107<https://github.com/PacificBiosciences/FALCON/pull/107>), but would you then be willing to switch to our new master branch?

**Comment by pb-jchin** [comment]
@rlleras  please make sure you check out this https://dazzlerblog.wordpress.com/2014/12/31/damapper-and-other-dazzler-upgrades/ 

the master branch now uses Gene's latest code.  You will have adjust the option for daligner. It supports the `-M` option now.  In the mean time, you will need to add `--output_dformat` for the `falcon_sense_option` in the configuration file.

**Comment by pb-cdunn** [comment]
Rebased and pulled.

**Pull request closed without merging**
