### PR TITLE
possible fix for an issue

### PR DESCRIPTION
**Pull request by pb-cdunn**
This is also a test of the code-review process. Please ignore (or turn off notifications) if you are not interested in seeing this.

Normally, we would also include a reference to the issue, as in `issue #64`, but I do not want to cause extra notifications right now.

### CODE REVIEW

**Comment by pb-jchin** [comment]
I think it is good for debugging the process. I like to incorporate such modification the the development branch (currently the "diconsensus" branch).  I might need to do a manually merging for this.

**Comment by pb-cdunn** [comment]
I'Il rebase to `diconsensus`.

Would you rather see Pull-Requests at your pb-chin account?

**Comment by pb-jchin** [comment]
yes, I can handle this.

**Comment by pb-cdunn** [comment]
Rebasing to `dicon`.

**Pull request closed without merging**
