### PR TITLE
minor fixes for debugging

### PR DESCRIPTION
**Pull request by pb-cdunn**
I had a good Travis run with this!

* https://travis-ci.org/pb-cdunn/FALCON-integrate

### CODE REVIEW

**Comment by pb-jchin** [comment]
Is the log file for each individual jobs be the standard out from the commit bcff31f?  I think this may be problematic for big jobs.  For large genome assembly, there will be >500 jobs.  It is still useful to separate  log files to figure where some the system failure may happen to some individual jobs.

**Comment by pb-cdunn** [comment]
I didn’t eliminate logging at all. What I did was store that output one script higher. run_script() captures all output for script.sh in script.sh.log (for local runs) or in sge_log (for Grid runs). It needs to be at that level so that Python can also capture it, which is essential for debugging anything in Travis.

I also didn't combine any logging. Each job has its own logfile.

Just try it. I don’t think you’ll find anything missing. I just tried E.coli and saw everything in sge_log.

There is a problem though. If big jobs produce lots of output, that is a lot of info written to disk. That is not a sudden change, but it might be a problem. I've exacerbated the problem by passing that output across the network, but it's a network filesystem so using the socket is probably not much worse that writing directly to a file. Minimizing output to what we really need for debugging is a good long-term goal.

**Comment by pb-jchin** [comment]
Yes. I know the log goes to `seg_log`. However, it will be hard to figure out which is which. You will need to log the job_name if you want to send the log the stdout and in `seg_log`.  This is from my experience figure several corrupted files out of > 1Mb files.  I do prefer to see the log is clearly assocatied with the job directory.

**Comment by pb-cdunn** [comment]
What about a symlink? Or we can append the job_id to the bash script and make that the job-name. That way, the sge_log filename would be the same as the script name, thus easy to find.

**Comment by pb-jchin** [comment]
make seg_log filename search is a good resolution.

**Pull request merged**
