### PR TITLE
Mains

### PR DESCRIPTION
**Pull request by pb-cdunn**
By moving the contents of the executables into `src/py/mains/...`, we have the potential to unit-test them.

So far, I am only checking `--help` on the modules which have it, but that's something.

The modules which depend on **pypeFLOW** cannot be tested. (We could *mock* **pypeFLOW** using **pymock**, but it's better to refactor first.)

### CODE REVIEW

**Comment by pb-jchin** [comment]
no problem for change the location of the directory. I do prefer the prefix "fc_".   Ideally, I hope all scripts can be called with as subcommand of one main script. This gives a sense of some name space to set to scope of the command line tools.  (The side effiect now is there will be many document changes...)

**Comment by pb-cdunn** [comment]
`fc_*` is used because executables are in a flat namespace, installed directly in the `bin` directory. Modules have directory hierarchy. So it makes more sense to rename `mains/` to `fc_mains/` or to `mains_fc`. That's also an easier change to make. How important is `mains/fc_*.py`?

Yes, combining scripts into one with subcommands is pretty simple.

>  (The side effiect now is there will be many document changes...) 

I don't understand. The documents should not need to change with this PR. Do you mean that docs would need to change if scripts were combined into one?

**Comment by pb-cdunn** [comment]
Note:
```
$ git diff --stat -C -C 0c3d729
 .gitmodules => src/py/mains/__init__.py                                   | 0
 src/{py_scripts/fc_actg_coordinate.py => py/mains/actg_coordinate.py}     | 0
 src/{py_scripts/fc_consensus.py => py/mains/consensus.py}                 | 0
 src/{py_scripts/fc_contig_annotate.py => py/mains/contig_annotate.py}     | 0
 src/{py_scripts/fc_ctg_link_analysis.py => py/mains/ctg_link_analysis.py} | 0
 src/{py_scripts/fc_graph_to_contig.py => py/mains/graph_to_contig.py}     | 0
 src/{py_scripts/fc_graph_to_utgs.py => py/mains/graph_to_utgs.py}         | 0
 src/{py_scripts/fc_ovlp_filter.py => py/mains/ovlp_filter.py}             | 0
 src/{py_scripts/fc_ovlp_stats.py => py/mains/ovlp_stats.py}               | 0
 src/{py_scripts/fc_ovlp_to_graph.py => py/mains/ovlp_to_graph.py}         | 0
 src/{py_scripts/fc_run.py => py/mains/run.py}                             | 0
 src/{py_scripts/fc_run_LG.py => py/mains/run_LG.py}                       | 0
 12 files changed, 0 insertions(+), 0 deletions(-)
```
In other words, there is a commit with pure file-moves. That helps git-blame:
```
$ git blame -C -C src/py/mains/ovlp_stats.py
2ee3e223 src/py_scripts/fc_ovlp_stats.py     (Christopher Dunn 2015-05-13  1) from falcon_kit.multiproc import Pool
2ee3e223 src/py_scripts/fc_ovlp_stats.py     (Christopher Dunn 2015-05-13  2) import argparse
e67eb010 src/py_scripts_v2/fc_ovlp_stats.py  (pb-jchin         2014-11-30  3) import subprocess as sp
...
91f22ae5 src/py_scripts/fc_ovlp_stats.py     (pb-jchin         2015-05-20 18)         for l in sp.check_output(shlex.split("LA4Falcon -mo ../1-preads_ovl/pr
e67eb010 src/py_scripts_v2/fc_ovlp_stats.py  (pb-jchin         2014-11-30 19)             l = l.strip().split()
e67eb010 src/py_scripts_v2/fc_ovlp_stats.py  (pb-jchin         2014-11-30 20)             q_id, t_id = l[:2]
e67eb010 src/py_scripts_v2/fc_ovlp_stats.py  (pb-jchin         2014-11-30 21)
c2b6159d src/py_scripts/fc_ovlp_stats.py     (pb-jchin         2015-06-24 22)             if q_id != None and q_id != current_q_id and q_l > 0:
...
```
You have to use `-C -C` so that git will try *harder* to find moves/copies.

**Comment by pb-jchin** [comment]
The problem is "graph_to_contig" or "ovlp_to_graph", etc, are generic.  With a prefix, it is easier to reference all at once rather than list them one by one in documentation. I have written a lot of note using that convention, now they will need to be all changed again. I think it is very useful the command line tools from Falcon with a recognizable prefix unless we put every thing as subcommands.

**Comment by pb-jchin** [comment]
never mind, I see what you did. as long as the command line interface starts with "fc_*" it is all good.

**Pull request merged**
