### PR TITLE
DBsplit with -a always

### LINKED ISSUE #294: Add -a to DBsplit always
While working on PacificBiosciences/DALIGNER#19, I noticed something interesting. I thought I'd found a bug in Gene's "Count" field, since it differed for trimmed vs. untrimmed (DBstats -u). E.g.
```
        Bin:      Count  % Reads  % Bases     Average
$ DBstats raw_reads|tail
      9,000:     40,863     46.2     78.0       20045
      8,000:     40,914     51.8     82.0       18804
      7,000:     43,978     57.8     85.8       17634
      6,000:     49,318     64.5     89.4       16474
      5,000:     55,371     72.0     92.9       15326
      4,000:     58,306     79.9     95.9       14252
      3,000:     53,730     87.2     98.1       13353
      2,000:     40,214     92.7     99.3       12714
      1,000:     33,201     97.2     99.8       12193
          0:     20,362    100.0    100.0       11876
$ DBstats -u raw_reads|tail
      9,000:     51,427     36.4     73.9       19507
      8,000:     53,708     41.1     78.1       18248
      7,000:     59,691     46.3     82.1       17036
      6,000:     68,100     52.2     86.2       15834
      5,000:     78,598     59.1     90.1       14632
      4,000:     86,221     66.6     93.6       13486
      3,000:     88,165     74.3     96.4       12451
      2,000:     83,590     81.6     98.3       11561
      1,000:     87,883     89.3     99.5       10695
          0:    122,132    100.0    100.0        9600
```
I expected only the "0" bin Count to change, since "untrimmed" will include reads < 500B. But they *all* change. I dove into his code and discovered that DBstats without -u will exclude even more if the 'all' flag is unset. We ran DBsplit this way:

    DBsplit -x500 -s200 raw_reads

It's missing '-a', which really should be there by default for PacBio data. The extra well reads are excellent for consensus, since they are on the same ring. And it's possible that wells with multiple reads represent the better Sequel data. (Just a hunch. Am I wrong?) So adding '-a' to 'pa_DBsplit_option' might give us better results. That would only *exacerbate* the problem of too much data, but it's still a good idea.

I'll add code to add it always, since I cannot think of a scenario where we wouldn't want the "secondary" well reads.

### PR DESCRIPTION
**Pull request by pb-cdunn**
Resolves #294.

### CODE REVIEW

**Comment by pb-jchin** [comment]
I still feel it is better to left it for configuration.  In some subtle case, with `-a` can help to remove chimera. Basically, the original design is the pass all configuration transparently to `DBSplit`.

**Comment by pb-cdunn** [comment]
You mean " In some subtle case, with*out* -a can help to remove chimera."? Ok.

But it seems like it is often left out by accident. Usually we want it. I certainly don't mind throwing PR away, but I don't like wondering whether its absence was intentional.

**Comment by pb-jchin** [comment]
yes.. sorry to get it wrong.  Yes. In very long read library, with "-a" and without "-a" should have very little different. For shorter insert library, you get more reads with "-a" but there is some risk that smaller insert with chimera self-correct inside the same molecule.  I don't mind to make `-a` default. The hard part is how to not specify it.  It needs change on the `DBsplit` code to make `-a` default.

**Comment by pb-cdunn** [comment]
Oh, so what you really want is a `-A` to turn *off* `-a`, overriding any `-a`. I'll do that quickly.

Could you explain more about these "secondary reads" for a given well? When does it happen? Why is it ever bad? A link maybe? I'm very curious, and I obviously have misunderstood something.

**Pull request closed without merging**
