### PR TITLE
use_tmpdir

### PR DESCRIPTION
**Pull request by pb-cdunn**
On some systems, there may be an advantage to running daligner on db files in /tmp. This is a re-working (by cdunn) of an idea from @yunfeiguo. See discussion at end of #152.

The new config is:
```
[General]
use_tmpdir = True
```
I have not measured any improvement on our fileservers, but it could be significant elsewhere.

### CODE REVIEW

**Comment by yunfeiguo** [comment]
I didn't test the performance improvement, but at least, the I/O wait on our NFS storage node dropped from 70~80% to <10% by using local file staging.

**Comment by yunfeiguo** [comment]
Looks like falcon will copy input files for each `daligner` job. Since all `daligner` jobs (in `0-rawreads`) use the same set of input files, is it possible to copy just once?

Also, we have found that copying input files to local `/tmp` for `LAmerge` and `falcon_consensus` jobs help reduce I/O load a lot because NFS is not good at handling many small requests.

**Comment by pb-cdunn** [comment]
> Looks like falcon will copy input files for each daligner job. Since all daligner jobs (in 0-rawreads) use the same set of input files, is it possible to copy just once?

Actually, it uses **rsync**, so it will be copied only once. The real problem is that two jobs could rsync simultaneously. I wanted to give you something quickly, so I've put off solving this for a bit. The simple solution is:

    flock my.lock -c "rsync ..."

But that will not work on NFS. I'm afraid we need a slightly complicated way to handle locking.

> Also, we have found that copying input files to local /tmp for LAmerge and falcon_consensus jobs help reduce I/O load a lot because NFS is not good at handling many small requests.

I figured that would be a good idea. I just wanted to get you the first thing first. Do you copy the `*.las` files somewhere in your code?

Btw, I have measured a speed-up of 10s for a 2m run, which is better than nothing. But as you say, the real win is in improving overall network performance.

**Comment by yunfeiguo** [comment]
I looked into `rj*.sh` files in `job_*` folders, and found that `rsync` destination is different from job to job. Is this expected?
```
rsync -av /home/yunfeiguo/Downloads/falcon_install/yunfeiguo_falcon_integrate_installation/FALCON-examples/run/ecoli/0-rawreads/.raw_reads.idx /tmp/falcon/_home_yunfeiguo_Downloads_falcon_install_yunfeiguo_falcon_integrate_installation_FALCON-examples_run_ecoli_0-rawreads_job_58de803e/.raw_reads.idx
rsync -av /home/yunfeiguo/Downloads/falcon_install/yunfeiguo_falcon_integrate_installation/FALCON-examples/run/ecoli/0-rawreads/.raw_reads.idx /tmp/falcon/_home_yunfeiguo_Downloads_falcon_install_yunfeiguo_falcon_integrate_installation_FALCON-examples_run_ecoli_0-rawreads_job_1e171e62/.raw_reads.idx
```

For `*.las` files, please take a look at 

https://github.com/WangGenomicsLab/FALCON/blob/master/src/py_scripts/fc_run.py#L478
https://github.com/WangGenomicsLab/FALCON/blob/master/src/py_scripts/fc_run.py#L309

**Comment by pb-cdunn** [comment]
No, not expected. I need to derive the tmp folder from the parent directory name. Just a sec...

**Pull request merged**
