### PR TITLE
Fix pread aln type

### PR DESCRIPTION
**Pull request by cschin**
The current behavior is not quite right. When `input_type = raw` is used in the configuration, the current code map raw sequences to each other using `daligner_p`, this is not the correct behavior unless there is true new algorithm development that I don't know about.  Setting the type for the argument will fix the bug. With the `type=int`, python interprets character `0` as True.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Looking....

(But for this PR, the "diff" is way off. You'd have to rebase your branch first.)

**Comment by pb-cdunn** [comment]
```
263 def get_script_xformer(pread_aln):
264     if pread_aln:
265         return xform_script_for_preads
266     else:
267         return xform_script_for_raw_reads
```
Aha! Thanks, Jason.

**Comment by cschin** [comment]
@pb-cdunn  I was making PR against the master here.... is the long PR due to the master is behind?

**Comment by pb-cdunn** [comment]
I think that's right. `master` is updated only when we have a smrttools release.

Best bet is to submit a PR vs. `develop`. Then, I won't be able to merge it here (since that would cause a conflict with `develop` in our bitbucket), but I can merge it into `develop` myself.

**Pull request closed without merging**
