### PR TITLE
LSF support

### PR DESCRIPTION
**Pull request by Imoteph**
Adds LSF support for FALCON!

To work with LSF parameters in the cfg  has to be changed:

job_type=LSF
sge_option_da = -n 8 -q %(jobqueue)s
sge_option_la = -n 2 -q %(jobqueue)s
sge_option_pda = -n 8 -q %(jobqueue)s
sge_option_pla = -n 2 -q %(jobqueue)s
sge_option_fc = -n 24 -q %(jobqueue)s
sge_option_cns = -n 8 -q %(jobqueue)s

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Squashed and pushed. Thanks!

**Comment by ebioman** [comment]
First, thank you very much for supporting LSF.
I have 2 questions though:
 1.  has this been tested extensively and is ready for a productive use or very early testing ?
 2.  regarding FALCON-integrate, this is not yet part of it as FALCON-integrate uses an earlier version.
Do you think it is safe to use for FALCON-integrate already this commit or are there other parts necessary to update first ? I am asking as a user asked for FALCON-integrate being installed on a LSF cluster.

Cheers

**Comment by Imoteph** [comment]
Hi, at least it runs at our cluster, as stated you have to make the adjustment in the cfg as well. 

Regarding FALCON-integrate, I hope #pb-cdunn is taking the changes as well there. But from currently the commit is only valid for this branch.

**Comment by pb-cdunn** [comment]
I think that commit will work. I am also working on a more recent release of **FALCON-integrate**, but I have to deal with updated dependencies.

**Comment by ebioman** [comment]
Hi
I am trying it currently and running in some issues - not sure where they stem from.
If I try to run FALCON (latest commit) with fc_run it succeeds for a moment and then obviously 
complains that it has no SGE and quits. If I correct the config according to your example and try fc_run it obviously fails 

<pre><code>
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
        section: [General]
        option : sge_option_da
        key    : jobqueue
        rawval : -n 8 -q %(jobqueue)s
</code></pre>

But if I try now to run with fc_run1 (if I understood correctly that's the one I have to use ?)
then it fails immediately due to pypeflow problems:

<pre><code>
 fc_run1 test.config 
Traceback (most recent call last):
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/bin/fc_run1", line 9, in <module>
    load_entry_point('falcon-kit==0.5', 'console_scripts', 'fc_run1')()
  File "/software/lib/python2.7/site-packages/pkg_resources.py", line 348, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/software/lib/python2.7/site-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/software/lib/python2.7/site-packages/pkg_resources.py", line 2025, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/software/UHTS/PacBio/FALCON-integrate/0.4.0/lib64/python2.7/site-packages/falcon_kit/mains/run1.py", line 4, in <module>
    from pypeflow.pwatcher_bridge import PypeProcWatcherWorkflow, MyFakePypeThreadTaskBase
ImportError: No module named pwatcher_bridge
</code></pre>

Which I find confusing as I thought that this is part of the pypeflow package and ``python -c 'import pypeflow'`` succeeds,,,

Essentially I just replaced FALCON in FALCON-integrate with the current commit. Is it possible that similarly I have to change as well for pypeflow (and possible DALIGNER or DAZZ_DB) ?

My Config:




<pre><code>
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

#job_type=LSF
sge_option_da = -n 8 -q %(jobqueue)s
sge_option_la = -n 2 -q %(jobqueue)s
sge_option_pda = -n 8 -q %(jobqueue)s
sge_option_pla = -n 2 -q %(jobqueue)s
sge_option_fc = -n 24 -q %(jobqueue)s
sge_option_cns = -n 8 -q %(jobqueue)s

#sge_option_da = -pe smp 8 -q jobqueue
#sge_option_la = -pe smp 2 -q jobqueue
#sge_option_pda = -pe smp 8 -q jobqueue
#sge_option_pla = -pe smp 2 -q jobqueue
#sge_option_fc = -pe smp 24 -q jobqueue
#sge_option_cns = -pe smp 8 -q jobqueue

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -dal24 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal24 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
</code></pre>

**Comment by pb-cdunn** [comment]
We use the standard Python `ConfigParser` module, which performs substitutions. Google that. Then simply provide `jobqueue` in your `[General]` section, or delete references to jobqueue from your `sge_option_*`.

**Comment by kassammo** [comment]
Dear all

I have downloaded the new version of Falcon, did someone find a way to run with LSF ?

Thanks a lot

**Pull request closed without merging**
